name: Hello World RPM Package
on: workflow_dispatch

jobs:
    package_rpm:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Package RPM and SRPM
          uses: xmidt-org/rpm-package-action@v1
          with:
            path: .
            spec: hello-world.spec
            distro: rocky-8
