name: Hello World RPM
on: workflow_dispatch

jobs:
    package_rpm:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Package RPM and SRPM
          uses: xmidt-org/rpm-package-action@v1
          with:
            path: ./hello-world
            spec: hello-world.spec
            distro: rocky-8
            # ubuntu-20.04 failes

        - name: ls
          run: ls -R .; ls /root/rpmbuild/RPMS/x86_64/hello-world-1-2.x86_64.rpm

        - uses: actions/upload-artifact@v3
          with:
            name: hello-world
            path: ./hello-world//output/hello-world-1-1.x86_64.rpm

