name: Hello World RPM Package
on: workflow_dispatch

jobs:
    package_rpm:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Package RPM and SRPM
          uses: xmidt-org/rpm-package-action@v1
          with:
            path: .
            spec: hello-world.spec
            distro: rocky-8
            # ubuntu-20.04

        - uses: actions/upload-artifact@v3
          with:
            name: hello-world-1-1.x86_64.rpm
            path: .

