name: libemcached build

on: workflow_dispatch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build-with-vagrant:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: preparation
      run: vagrant up
      
    - name: fetch libmemcached and untar
      run: vagrant ssh -- /vagrant/fetch_libmemcached.sh

    - name: build libmemcached
      run: vagrant ssh -- /vagrant/build_libmemcached.sh

  build-with-runs-on:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: preparation
      run: ./apt_gets.sh

    - name: fetch libmemcached and untar
      run: ./fetch_libmemcached.sh

    - name: build libmemcached
      run: ./build_libmemcached.sh
