name: libemcached build

on: workflow_dispatch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install virtualbox and vagrant
      run: |
        sudo apt install virtualbox
        sudo apt install vagrant

    - name: vagrant up
      run: vagrant up
      
    - name: fetch libmemcached and untar
      run: vagrant ssh -- /vagrant/fetch_libmemcached.sh

    - name: build and install libmemcached
      run: vagrant ssh -- /vagrant/build_libmemcached.sh
