name: libemcached build

on: workflow_dispatch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: wget libmemcached-1.0.18
      run: wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz

    - name: tar -zxf libmemcached-1.0.18.tar.gz
      run: tar -zxf libmemcached-1.0.18.tar.gz

    - name: configure
      run: cd libmemcached-1.0.18.tar.gz; ./configure --prefix=/usr/local/libmemcached --enable-memaslap

    - name: fix up memflush.cc
      run: cd libmemcached-1.0.18.tar.gz; sed -i 's/opt_servers == false/opt_servers == NULL/g' clients/memflush.cc

    - name: Run make
      run: export LDFLAGS="-L/lib64 -lpthread"; cd libmemcached-1.0.18.tar.gz; make && make test

    - name: Run install
      run: cd libmemcached-1.0.18.tar.gz; sudo make install
