name: libemcached build

on: workflow_dispatch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: vagrant up
    #  run: vagrant up
      
    - name: wget libmemcached-1.0.18 and untar
      run: |
        wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz
        tar -zxf libmemcached-1.0.18.tar.gz

    - name: configure and make
      run: |
        export LDFLAGS="-L/lib64 -lpthread"; 
        cd libmemcached-1.0.18; 
        ./configure --enable-memaslap;
        sed -i 's/opt_servers == false/opt_servers == NULL/g' clients/memflush.cc;
        make && make test

    - name: Run install
      run: cd libmemcached-1.0.18; sudo make install
