name: libemcached build

on: workflow_dispatch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build-here:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: all in one
      run: |
        ls -l;
        apt_gets.sh;
        fetch_libmemcached.sh;
        build_libmemcached.sh

  build-with-vagrant:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: install virtualbox and vagrant
      run: |
        #sudo apt-get update
        #sudo apt-get install -y virtualbox
        #sudo apt-get install -y vagrant
        brew cask install virtualbox
        brew cask install vagrant
        
    - name: vagrant up
      run: vagrant up
      
    - name: fetch libmemcached and untar
      run: vagrant ssh -- /vagrant/fetch_libmemcached.sh

    - name: build and install libmemcached
      run: vagrant ssh -- /vagrant/build_libmemcached.sh

