name: libemcached build

on: workflow_dispatch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: vagrant up
    #  run: vagrant up
      
    - name: fetch libmemcached and untar
      run: fetch_libmemcached.sh

    - name: build and install libmemcached
      run: build_libmemcached.sh
