name: memaslap

on: push
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build-with-vagrant:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: memaslap
      run: vagrant up; vagrant ssh -- 'cp /vagrant/* .; ~/build_memaslap.sh'
      
  build-with-runs-on:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: memaslap
      run: ./apt_gets.sh; ./build_memaslap.sh

#    - name: Package RPM and SRPM
#      uses: xmidt-org/rpm-package-action@v1
#      with:
#          path: .
#          spec: memaslap.spec
#          distro: rocky-8

#    - name: ls
#      run: ls -R .

#    - uses: actions/upload-artifact@v3
#      with:
#          name: memaslap
#          path: ./output/memaslap-1.0.18-1.x86_64.rpm

